# Generated by Django 2.1.2 on 2021-03-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20210328_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
